# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'road_parameters.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(421, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.lanes_amount = QtWidgets.QLineEdit(Dialog)
        self.lanes_amount.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lanes_amount.setObjectName("lanes_amount")
        self.gridLayout.addWidget(self.lanes_amount, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setEnabled(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 8, 0, 2, 1)
        self.is_destination = QtWidgets.QCheckBox(Dialog)
        self.is_destination.setChecked(True)
        self.is_destination.setObjectName("is_destination")
        self.gridLayout.addWidget(self.is_destination, 7, 0, 1, 1)
        self.percentage_dest = QtWidgets.QLineEdit(Dialog)
        self.percentage_dest.setObjectName("percentage_dest")
        self.gridLayout.addWidget(self.percentage_dest, 8, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 11, 3, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 12, 0, 1, 6)
        self.ignore_limit = QtWidgets.QCheckBox(Dialog)
        self.ignore_limit.setObjectName("ignore_limit")
        self.gridLayout.addWidget(self.ignore_limit, 2, 1, 1, 1)
        self.random_cars = QtWidgets.QCheckBox(Dialog)
        self.random_cars.setChecked(True)
        self.random_cars.setObjectName("random_cars")
        self.gridLayout.addWidget(self.random_cars, 2, 0, 1, 1)
        self.car_spawn_num = QtWidgets.QLineEdit(Dialog)
        self.car_spawn_num.setEnabled(True)
        self.car_spawn_num.setObjectName("car_spawn_num")
        self.gridLayout.addWidget(self.car_spawn_num, 5, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 10, 0, 1, 1)
        self.destination_priority = QtWidgets.QLineEdit(Dialog)
        self.destination_priority.setObjectName("destination_priority")
        self.gridLayout.addWidget(self.destination_priority, 10, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Amount of cars to spawn"))
        self.label_3.setText(_translate("Dialog", "% of all destination will be this road"))
        self.is_destination.setText(_translate("Dialog", "Can be destination"))
        self.label.setText(_translate("Dialog", "Lanes amount"))
        self.ignore_limit.setText(_translate("Dialog", "Ignore global spawn limit"))
        self.random_cars.setText(_translate("Dialog", "Random amount of cars"))
        self.label_4.setText(_translate("Dialog", "Destination priority"))
